stages:
    - test

sudo: false
os: linux

language: node_js
node_js:
    - 10

cache:
    yarn: true
    directories:
        - node_modules

before_install:
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - export PATH="$HOME/.yarn/bin:$PATH"

install: yarn install

jobs:
    include:
        - stage: test
          script: yarn test -- --coverage
          after_script: bash <(curl -s https://codecov.io/bash)
