version: '3.2'

services:
  web:
    image: node:8.9-alpine
    environment:
      NODE_ENV: development
    volumes:
      - .:/usr/src/app
    command: yarn start
    working_dir: /usr/src/app
    ports:
      - 80:3000
